# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-02-13T11:29:27Z"
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: kibana
  name: kibana-kibana
  namespace: kube-system
  resourceVersion: "5609"
  uid: 0ca1fbbe-17e6-4692-84fd-5146e7e322f3
spec:
  clusterIP: 10.102.176.75
  clusterIPs:
  - 10.102.176.75
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5601
    protocol: TCP 
    targetPort: 5601
    nodePort: 30560
  selector:
    app: kibana
    release: kibana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
